### ISSUE TITLE
Add more detail on gromacs benzene dataset descr

### ISSUE THREAD

**Issue by dotsdl** [alchemistry/alchemtest#1]
The [``descr.txt``](https://github.com/alchemistry/alchemtest/blob/master/src/alchemtest/gmx/benzene/descr.txt) for the Gromacs benzene dataset is a bit of a stub, and could use more detail, such as on:
* system size
* alchemical pathway
* temperature
* and anything else important for usage

Even a little ASCII diagram showing the alchemical pathway would help.

**Comment by dotsdl** [comment]
@ianmkenney would you mind taking this on, since this is your dataset?

**Comment by dotsdl** [comment]
Addressed by 90b07dd4578c0d8319097256f8eb11d66e2188a2.

**Comment by dotsdl** [comment]
@ianmkenney can you please add the expected solvation free energy for benzene in water in units of `kT`, with a reference, to the DESCR? This would give us a "right answer" to directly compare to. Could even make this an attribute of the data `Bunch`, too.

**Comment by orbeckst** [comment]
We didn't include a "right" answer for the Amber data #5 either. Philosophically, that's also a problem because this will depend on the method that is used to calculate the "right" answer from the data. For the tests, this is the reference value and it should _live in the test case_. Whoever writes the test will determine what the correct reference value for the method and parameters is going to be.

I think it is enough to include an experimental value, if one is available, to get a sense where the computed value should come down.
